import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";

import { BubblesCanvas } from "@/components/bubbles/bubblesCanvas";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import { BackgroundCanvas } from "@/components/shader-background/BackgroundCanvas";
import SideMenu from "@/components/sideMenu/SideMenu";

const creamCake = localFont({
  variable: "--font-cream-cake",
  src: "../../public/font/Cream Cake.otf",
});

const poppins = localFont({
  variable: "--font-poppins",
  src: "../../public/font/poppins-extrabold.ttf",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${creamCake.variable} scrollbar scrollbar-none overflow-x-hidden antialiased`}
      >
        <BackgroundCanvas />
        <BubblesCanvas />

        <Header />
        <SideMenu />
        <main className="bg-primary">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
